services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Project
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb
    container_name: mysql_retry
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: